profiles:
    splunk:
        connector: splunk
        connection:
            host: SplunkServerDefaultCert # Updated host to 'SplunkServerDefaultCert' to bypass SSL errors caused by the default self-signed certificate in Splunk, which was triggering validation issues with the subjectAltName in the SSL certificate.
            port: 8089
            #selfSignedCert: false
            options:  # use any of this section when needed
                verify_cert: false  # allow invalid/self-signed 
                validate_pattern: true
                stix_validator: true
                index: main
                stix_2.1: true
                retrieval_batch_size: 10000
                cool_down_after_transmission: 1  # seconds to cool down between data source API calls, required by some API such as sentinelone; Kestrel default: 0
                allow_dev_connector: True  # do not check version of a connector to allow custom/testing connector installed with any version; Kestrel default: False
        config:
            auth:
                username: $SPLUNK_USERNAME
                password: $SPLUNK_PASSWORD
options:
    translation_workers_count: 8  # default: 2
